- Container1:
    Control: GroupContainer@1.3.0
    Variant: ManualLayout
    Properties:
      Height: =Parent.Height
      Width: =Parent.Width
    Children:
      - Gallery1:
          Control: Gallery@2.15.0
          Variant: BrowseLayout_Vertical_ThreeTextVariant_ver5.0
          Properties:
            Height: =568
            Items: "=If(\n    IsBlank(indexDB1.colDataOut),\n    Blank(),\n    AddColumns(\n        Table(ParseJSON(First(Filter(AddColumns(Table(ParseJSON(indexDB1.colDataOut)),colName,Text(Value.colName),colData,Text(Value.colData)),colName = \"col_demo\")).colData)),\n        \n        rowID, Text(Value.rowID),\n        Data, Text(Value.Data),\n        Loaded, Text(Value.Loaded)\n    )\n)"
            Width: =590
            Y: =200
          Children:
            - Title3:
                Control: Label@2.5.1
                Properties:
                  BorderColor: =RGBA(0, 0, 0, 1)
                  Color: =RGBA(50, 49, 48, 1)
                  FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                  Height: =Self.Size * 1.8
                  OnSelect: =Select(Parent)
                  PaddingBottom: =0
                  PaddingLeft: =0
                  PaddingRight: =0
                  PaddingTop: =0
                  Size: =14
                  Text: =ThisItem.rowID
                  VerticalAlign: =VerticalAlign.Top
                  Width: =Parent.TemplateWidth - 86
                  X: =16
                  Y: =(Parent.TemplateHeight - (Self.Size*1.8 + Subtitle3.Size*1.8 + 2 + Body1.Size*1.8)) / 2
            - Subtitle3:
                Control: Label@2.5.1
                Properties:
                  BorderColor: =RGBA(0, 0, 0, 1)
                  FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                  Height: =Self.Size * 1.8
                  OnSelect: =Select(Parent)
                  PaddingBottom: =0
                  PaddingLeft: =0
                  PaddingRight: =0
                  PaddingTop: =0
                  Size: =12
                  Text: =ThisItem.Data
                  VerticalAlign: =VerticalAlign.Top
                  Width: =Title3.Width
                  X: =Title3.X
                  Y: =Title3.Y + Title3.Height
            - Body1:
                Control: Label@2.5.1
                Properties:
                  BorderColor: =RGBA(0, 0, 0, 1)
                  FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                  Height: =Self.Size * 1.8
                  OnSelect: =Select(Parent)
                  PaddingBottom: =0
                  PaddingLeft: =0
                  PaddingRight: =0
                  PaddingTop: =0
                  Size: =12
                  Text: =ThisItem.Loaded
                  VerticalAlign: =VerticalAlign.Top
                  Width: =Title3.Width
                  X: =Title3.X
                  Y: =Subtitle3.Y + Subtitle3.Height
            - NextArrow3:
                Control: Classic/Icon@2.5.0
                Properties:
                  AccessibleLabel: =Self.Tooltip
                  Color: =RGBA(166, 166, 166, 1)
                  Height: =50
                  Icon: =Icon.ChevronRight
                  OnSelect: =Select(Parent)
                  PaddingBottom: =16
                  PaddingLeft: =16
                  PaddingRight: =16
                  PaddingTop: =16
                  Tooltip: ="View item details"
                  Width: =50
                  X: =Parent.TemplateWidth - Self.Width - 12
                  Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
            - Separator3:
                Control: Rectangle@2.3.0
                Properties:
                  Fill: =RGBA(255, 255, 255, 1)
                  Height: =8
                  OnSelect: =Select(Parent)
                  Width: =Parent.TemplateWidth
                  Y: =Parent.TemplateHeight - Self.Height
            - Rectangle3:
                Control: Rectangle@2.3.0
                Properties:
                  Fill: =App.Theme.Colors.Darker30
                  Height: =Parent.TemplateHeight - Separator3.Height
                  OnSelect: =Select(Parent)
                  Visible: =ThisItem.IsSelected
                  Width: =4
      - indexDB1:
          Control: CodeComponent
          ComponentName: belleye_Belleye.indexDB
          Properties:
            OnChange: =UpdateContext({ctx_indexDB_writeAction:false,ctx_indexDB_colName:"*"})
            X: =1166
            colData: =ctx_indexDB_colData
            colName: =ctx_indexDB_colName
            writeAction: =ctx_indexDB_writeAction
      - cnt_Buttons:
          Control: GroupContainer@1.3.0
          Variant: AutoLayout
          Properties:
            LayoutDirection: =LayoutDirection.Vertical
            LayoutGap: =5
            Width: =209
          Children:
            - btn_CreateData:
                Control: Button@0.0.44
                Properties:
                  OnSelect: |+
                    =Clear(col_demo);
                    ForAll(
                        Sequence(Slider1.Value*1000, 1, 1),
                        Collect(col_demo, { rowID: ThisRecord.Value, Data: GUID(), Loaded:Now() })
                    );
                  Text: ="Create Collection"
                  Width: =Parent.Width
                  X: =54
                  Y: =45
            - btn_SaveData:
                Control: Button@0.0.44
                Properties:
                  OnSelect: =UpdateContext({ctx_indexDB_colName:"col_demo",ctx_indexDB_colData:JSON(col_demo),ctx_indexDB_writeAction:true})
                  Text: ="Save Collection"
                  Width: =Parent.Width
                  X: =54
                  Y: =75
            - btn_ClearData:
                Control: Button@0.0.44
                Properties:
                  OnSelect: =UpdateContext({ctx_indexDB_colName:"*",ctx_indexDB_colData:Blank(),ctx_indexDB_writeAction:true})
                  Text: ="Clear Store"
                  Width: =Parent.Width
                  X: =54
                  Y: =163
            - btn_CollectFromStore:
                Control: Button@0.0.44
                Properties:
                  OnSelect: |-
                    =ClearCollect(
                        col_stored,
                        AddColumns(
                            Table(
                                ParseJSON(
                                    First(
                                        Filter(
                                            AddColumns(
                                                Table(ParseJSON(indexDB1.colDataOut)),
                                                colName,
                                                Text(Value.colName),
                                                colData,
                                                Text(Value.colData)
                                            ),
                                            colName = "col_demo"
                                        )
                                    ).colData
                                )
                            ),
                            rowID,
                            Text(Value.rowID),
                            Data,
                            Text(Value.Data)
                        )
                    )
                  Text: ="Collect from Store"
                  Width: =Parent.Width
                  X: =54
                  Y: =595
            - btn_GetData:
                Control: Button@0.0.44
                Properties:
                  OnSelect: =UpdateContext({ctx_indexDB_colName:"*",ctx_indexDB_colData:Blank(),ctx_indexDB_writeAction:false})
                  Text: ="Get All"
                  Width: =Parent.Width
                  X: =54
                  Y: =267
      - cnt_Variables:
          Control: GroupContainer@1.3.0
          Variant: AutoLayout
          Properties:
            DropShadow: =DropShadow.None
            Height: =768
            LayoutDirection: =LayoutDirection.Horizontal
            Width: =757
            X: =608
          Children:
            - Container3:
                Control: GroupContainer@1.3.0
                Variant: AutoLayout
                Properties:
                  DropShadow: =DropShadow.None
                  LayoutDirection: =LayoutDirection.Vertical
                Children:
                  - TextCanvas1:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.End
                        PaddingRight: =5
                        Text: ="colName:"
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
                  - TextCanvas1_1:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.End
                        PaddingRight: =5
                        Text: ="colData:"
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
                  - TextCanvas1_2:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.End
                        PaddingRight: =5
                        Text: ="writeAction:"
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
                  - TextCanvas1_4:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.End
                        PaddingRight: =5
                        Text: ="storageUsage:"
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
                  - TextCanvas1_3:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.End
                        PaddingRight: =5
                        Text: ="colDataOut:"
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
            - Container3_1:
                Control: GroupContainer@1.3.0
                Variant: AutoLayout
                Properties:
                  DropShadow: =DropShadow.None
                  LayoutDirection: =LayoutDirection.Vertical
                Children:
                  - TextCanvas1_5:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.Start
                        PaddingLeft: =5
                        Text: =indexDB1.colName
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
                  - TextCanvas1_6:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.Start
                        PaddingLeft: =5
                        Text: =indexDB1.colData
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
                  - TextCanvas1_7:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.Start
                        PaddingLeft: =5
                        Text: =indexDB1.writeAction
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
                  - TextCanvas1_9:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.Start
                        PaddingLeft: =5
                        Text: =Round(indexDB1.storageUsage, 2)&" mb"
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
                  - TextCanvas1_8:
                      Control: Text@0.0.50
                      Properties:
                        Align: ='TextCanvas.Align'.Start
                        AutoHeight: =true
                        PaddingLeft: =5
                        Text: =indexDB1.colDataOut
                        VerticalAlign: =VerticalAlign.Middle
                        Width: =Parent.Width
      - Slider1:
          Control: Slider@1.0.31
          Properties:
            Max: =50
            Min: =1
            X: =246
            Y: =40
      - TextCanvas3:
          Control: Text@0.0.50
          Properties:
            Align: ='TextCanvas.Align'.Center
            Height: =40
            Text: ="Create "&Slider1.Value&",000 Rows"
            VerticalAlign: =VerticalAlign.Middle
            Width: =200
            X: =246
